"""
THE EXECUTOR
============
Applies plans/creature_plan.json, quest_plan.json, and item_plan.json to the
live DB - or exports the equivalent SQL to a file instead of/as well as
applying it.

Safety defaults:
  - Dry-run unless you pass --apply. Dry-run prints every statement it WOULD run.
  - Creates timestamped backup tables before touching anything real.
  - Everything runs inside one transaction; a hard failure rolls back everything.
  - Clone-required creatures/items (shared with content outside the target
    maps) are skipped unless you pass --include-clones.

Usage:
  python executor.py                              # dry run, prints statements, writes nothing
  python executor.py --apply                       # actually write to the DB
  python executor.py --apply --include-clones       # also handle clones
  python executor.py --export-sql changes.sql       # write a standalone .sql file, don't touch the DB
  python executor.py --apply --export-sql changes.sql  # do both: apply AND keep a copy of the SQL
"""
import argparse
import json
import os
import time

from config import (PLAN_DIR, CLONE_ENTRY_OFFSET, CREATURE_STATE_TABLE, QUEST_STATE_TABLE,
                    ITEM_STATE_TABLE, SPELL_NERF_STATE_TABLE)
from db import get_connection, table_columns, resolve_column, ensure_state_table, mark_processed
import spell_lookup


class SQLWriter:
    """Collects fully-substituted, properly-escaped SQL statements as they're
    generated, so the whole run can be dumped to a standalone .sql file -
    reviewable before running, or runnable by hand outside this tool."""

    def __init__(self, conn, path):
        self.conn = conn
        self.path = path
        self.declared_tables = set()
        self.lines = [
            f"-- Generated by executor.py on {time.strftime('%Y-%m-%d %H:%M:%S')}",
            "-- Review before running. Wrapped in a transaction so it's all-or-nothing.",
            "START TRANSACTION;",
            "",
        ]

    def comment(self, text):
        self.lines.append(f"-- {text}")

    def statement(self, stmt, params=None):
        self.lines.append(self.render(stmt, params) + ";")

    def declare_state_table(self, table_name):
        """Emits the CREATE TABLE IF NOT EXISTS for a tracking table exactly
        once per export, no matter how many rows reference it."""
        if table_name in self.declared_tables:
            return
        self.declared_tables.add(table_name)
        self.statement(
            f"CREATE TABLE IF NOT EXISTS `{table_name}` ("
            f"entry_id BIGINT NOT NULL PRIMARY KEY, "
            f"detail VARCHAR(255) NULL, "
            f"applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
            f") ENGINE=InnoDB"
        )

    def mark_processed(self, table_name, entry_id, detail=""):
        """Emits the same tracking INSERT db.mark_processed() would run
        against a live connection - included in every export (dry-run or
        not) so a standalone-run .sql file still keeps future runs of
        brain.py/item_scaler.py idempotent, not just Python --apply runs."""
        self.declare_state_table(table_name)
        self.statement(
            f"INSERT INTO `{table_name}` (entry_id, detail) VALUES (%s, %s) "
            f"ON DUPLICATE KEY UPDATE detail = VALUES(detail), applied_at = CURRENT_TIMESTAMP",
            (entry_id, (detail or "")[:255]),
        )

    def render(self, stmt, params=None):
        if not params:
            return stmt
        escaped = [self.conn.escape(p) for p in params]
        parts = stmt.split("%s")
        if len(parts) - 1 != len(escaped):
            raise ValueError(f"Placeholder/param count mismatch rendering: {stmt!r} with {params!r}")
        out = []
        for i, e in enumerate(escaped):
            out.append(parts[i])
            out.append(str(e))
        out.append(parts[-1])
        return "".join(out)

    def flush(self):
        self.lines.append("")
        self.lines.append("COMMIT;")
        with open(self.path, "w", encoding="utf-8") as f:
            f.write("\n".join(self.lines) + "\n")


def load_plans():
    with open(os.path.join(PLAN_DIR, "creature_plan.json")) as f:
        creature_plan = json.load(f)
    with open(os.path.join(PLAN_DIR, "quest_plan.json")) as f:
        quest_plan = json.load(f)
    item_plan = {}
    item_plan_path = os.path.join(PLAN_DIR, "item_plan.json")
    if os.path.exists(item_plan_path):
        with open(item_plan_path) as f:
            item_plan = json.load(f)
    spell_plan = {}
    spell_plan_path = os.path.join(PLAN_DIR, "spell_plan.json")
    if os.path.exists(spell_plan_path):
        with open(spell_plan_path) as f:
            spell_plan = json.load(f)
    return creature_plan, quest_plan, item_plan, spell_plan


def make_backup(conn, source_table, dry_run, sql_writer=None):
    ts = time.strftime("%Y%m%d_%H%M%S")
    backup_name = f"{source_table}_backup_{ts}"
    stmt = f"CREATE TABLE `{backup_name}` AS SELECT * FROM `{source_table}`"
    print(f"[BACKUP] {stmt}")
    if sql_writer:
        sql_writer.comment(f"Backup of {source_table} before changes")
        sql_writer.statement(stmt)
    if not dry_run:
        with conn.cursor() as cur:
            cur.execute(stmt)
    return backup_name


def apply_creature_plan(conn, plan, dry_run, include_clones, sql_writer=None):
    cols = plan["columns"]["creature_template"]
    ccols = plan["columns"]["creature"]
    entry_col, minlvl_col, maxlvl_col = cols["entry"], cols["minlevel"], cols["maxlevel"]

    if not dry_run:
        ensure_state_table(conn, CREATURE_STATE_TABLE)
    if sql_writer:
        sql_writer.declare_state_table(CREATURE_STATE_TABLE)

    n_simple = n_cloned = 0

    if sql_writer:
        sql_writer.comment("=== Creatures: simple level updates ===")

    for rec in plan["simple"]:
        stmt = (
            f"UPDATE creature_template SET {minlvl_col} = %s, {maxlvl_col} = %s "
            f"WHERE {entry_col} = %s"
        )
        params = (rec["new_minlevel"], rec["new_maxlevel"], rec["entry"])
        print(f"[CREATURE] entry={rec['entry']} ({rec['name']}): "
              f"{rec['old_minlevel']}-{rec['old_maxlevel']} -> {rec['new_minlevel']}-{rec['new_maxlevel']}")
        if sql_writer:
            sql_writer.statement(stmt, params)
            sql_writer.mark_processed(CREATURE_STATE_TABLE, rec["entry"],
                                       f"{rec['old_minlevel']}-{rec['old_maxlevel']} -> "
                                       f"{rec['new_minlevel']}-{rec['new_maxlevel']}")
        if not dry_run:
            with conn.cursor() as cur:
                cur.execute(stmt, params)
            mark_processed(conn, CREATURE_STATE_TABLE, rec["entry"],
                            f"{rec['old_minlevel']}-{rec['old_maxlevel']} -> {rec['new_minlevel']}-{rec['new_maxlevel']}")
        n_simple += 1

    if include_clones:
        if sql_writer:
            sql_writer.comment("=== Creatures: clones (shared templates) ===")
        for rec in plan["cloned"]:
            with conn.cursor() as cur:
                cur.execute(f"SELECT * FROM creature_template WHERE {entry_col} = %s", (rec["entry"],))
                base_row = cur.fetchone()
            if not base_row:
                print(f"[CREATURE][SKIP] entry={rec['entry']} no longer exists, skipping clone")
                continue

            new_row = dict(base_row)
            new_row[entry_col] = rec["new_entry"]
            new_row[minlvl_col] = rec["new_minlevel"]
            new_row[maxlvl_col] = rec["new_maxlevel"]

            col_names = list(new_row.keys())
            placeholders = ", ".join(["%s"] * len(col_names))
            insert_stmt = (
                f"INSERT INTO creature_template ({', '.join('`' + c + '`' for c in col_names)}) "
                f"VALUES ({placeholders})"
            )
            insert_params = [new_row[c] for c in col_names]
            print(f"[CREATURE][CLONE] entry={rec['entry']} -> new_entry={rec['new_entry']} "
                  f"({rec['name']}), also spawns in maps {rec['also_spawns_in_maps']}")
            if sql_writer:
                sql_writer.statement(insert_stmt, insert_params)
            if not dry_run:
                with conn.cursor() as cur:
                    cur.execute(insert_stmt, insert_params)

            for guid in rec["spawn_guids_to_repoint"]:
                repoint_stmt = f"UPDATE creature SET {ccols['id']} = %s WHERE {ccols['guid']} = %s"
                repoint_params = (rec["new_entry"], guid)
                print(f"[CREATURE][REPOINT] guid={guid}: {ccols['id']} {rec['entry']} -> {rec['new_entry']}")
                if sql_writer:
                    sql_writer.statement(repoint_stmt, repoint_params)
                if not dry_run:
                    with conn.cursor() as cur:
                        cur.execute(repoint_stmt, repoint_params)
            if sql_writer:
                sql_writer.mark_processed(CREATURE_STATE_TABLE, rec["entry"], f"cloned -> {rec['new_entry']}")
            if not dry_run:
                mark_processed(conn, CREATURE_STATE_TABLE, rec["entry"], f"cloned -> {rec['new_entry']}")
            n_cloned += 1
    elif plan["cloned"]:
        print(f"[CREATURE] Skipping {len(plan['cloned'])} clone-required entries "
              f"(pass --include-clones to handle them).")

    return n_simple, n_cloned


def apply_quest_plan(conn, plan, dry_run, sql_writer=None):
    cols = plan["columns"]["quest_template"]
    id_col, level_col = cols["id"], cols["level"]
    minlevel_col, money_col = cols.get("minlevel"), cols.get("money")

    if not dry_run:
        ensure_state_table(conn, QUEST_STATE_TABLE)
    if sql_writer:
        sql_writer.declare_state_table(QUEST_STATE_TABLE)

    if sql_writer:
        sql_writer.comment("=== Quests ===")

    n = 0
    for rec in plan.get("quests", []):
        set_clauses = [f"{level_col} = %s"]
        params = [rec["new_level"]]
        if minlevel_col and rec.get("new_minlevel") is not None:
            set_clauses.append(f"{minlevel_col} = %s")
            params.append(rec["new_minlevel"])
        if money_col and rec.get("new_reward_money") is not None:
            set_clauses.append(f"{money_col} = %s")
            params.append(rec["new_reward_money"])
        params.append(rec["quest_id"])

        stmt = f"UPDATE quest_template SET {', '.join(set_clauses)} WHERE {id_col} = %s"
        note = f" [{rec['note']}]" if rec.get("note") else ""
        minlvl_str = f", minlevel {rec['old_minlevel']}->{rec['new_minlevel']}" if minlevel_col else ""
        money_str = f", money {rec['old_reward_money']}->{rec['new_reward_money']}" if money_col else ""
        print(f"[QUEST] id={rec['quest_id']} ({rec.get('title')}): "
              f"level {rec['old_level']}->{rec['new_level']}{minlvl_str}{money_str}{note}")
        if sql_writer:
            sql_writer.statement(stmt, params)
            sql_writer.mark_processed(QUEST_STATE_TABLE, rec["quest_id"], f"level {rec['old_level']}->{rec['new_level']}")
        if not dry_run:
            with conn.cursor() as cur:
                cur.execute(stmt, params)
            mark_processed(conn, QUEST_STATE_TABLE, rec["quest_id"],
                            f"level {rec['old_level']}->{rec['new_level']}")
        n += 1
    return n


def apply_item_plan(conn, plan, dry_run, include_clones, sql_writer=None):
    ic = plan.get("columns")
    if not ic:
        return 0, 0

    if not dry_run:
        ensure_state_table(conn, ITEM_STATE_TABLE)
    if sql_writer:
        sql_writer.declare_state_table(ITEM_STATE_TABLE)

    def build_set_clauses(rec):
        clauses, params = [], []
        if rec.get("new_item_level") is not None:
            clauses.append(f"{ic['itemlevel']} = %s")
            params.append(rec["new_item_level"])
        if rec.get("write_required_level", True):
            clauses.append(f"{ic['reqlevel']} = %s")
            params.append(rec["new_required_level"])
        for sv_col, new_val in rec.get("new_stat_values", {}).items():
            clauses.append(f"{sv_col} = %s")
            params.append(new_val)
        for st_col, new_type in rec.get("new_stat_types", {}).items():
            clauses.append(f"{st_col} = %s")
            params.append(new_type)
        for spellid_col in rec.get("cleared_spell_slots", []):
            clauses.append(f"{spellid_col} = %s")
            params.append(0)
        if rec.get("new_armor") is not None:
            clauses.append(f"{ic['armor']} = %s")
            params.append(rec["new_armor"])
        if rec.get("new_dmg_min") is not None:
            clauses.append(f"{ic['dmgmin']} = %s")
            params.append(rec["new_dmg_min"])
        if rec.get("new_dmg_max") is not None:
            clauses.append(f"{ic['dmgmax']} = %s")
            params.append(rec["new_dmg_max"])
        if rec.get("new_random_property") is not None and ic.get("randomproperty"):
            clauses.append(f"{ic['randomproperty']} = %s")
            params.append(rec["new_random_property"])
        if rec.get("new_random_suffix") is not None and ic.get("randomsuffix"):
            clauses.append(f"{ic['randomsuffix']} = %s")
            params.append(rec["new_random_suffix"])
        return clauses, params

    n_simple = n_cloned = 0

    if sql_writer:
        sql_writer.comment("=== Items: simple downscale (unshared items) ===")

    for rec in plan.get("simple", []):
        if not rec.get("resolved", True):
            continue
        clauses, params = build_set_clauses(rec)
        stmt = f"UPDATE item_template SET {', '.join(clauses)} WHERE {ic['entry']} = %s"
        params.append(rec["entry"])
        if rec.get("write_required_level", True):
            reqlevel_str = f"reqlevel {rec['old_required_level']}->{rec['new_required_level']}, "
        else:
            reqlevel_str = f"reqlevel unchanged (quest reward - {rec['new_required_level']} was reference-only), "
        print(f"[ITEM] entry={rec['entry']} ({rec['name']}): {reqlevel_str}"
              f"itemlevel {rec['old_item_level']}->{rec['new_item_level']}")
        if sql_writer:
            sql_writer.statement(stmt, params)
            sql_writer.mark_processed(ITEM_STATE_TABLE, rec["entry"],
                                       f"reqlevel {rec['old_required_level']}->{rec['new_required_level']}")
        if not dry_run:
            with conn.cursor() as cur:
                cur.execute(stmt, params)
            mark_processed(conn, ITEM_STATE_TABLE, rec["entry"],
                            f"reqlevel {rec['old_required_level']}->{rec['new_required_level']}")
        n_simple += 1

    if include_clones:
        if sql_writer:
            sql_writer.comment("=== Items: clones (shared items) ===")
        for rec in plan.get("cloned", []):
            if not rec.get("resolved", True):
                continue
            with conn.cursor() as cur:
                cur.execute(f"SELECT * FROM item_template WHERE {ic['entry']} = %s", (rec["entry"],))
                base_row = cur.fetchone()
            if not base_row:
                continue

            with conn.cursor() as cur:
                cur.execute(f"SELECT MAX({ic['entry']}) AS m FROM item_template")
                new_entry = (cur.fetchone()["m"] or 0) + CLONE_ENTRY_OFFSET + n_cloned

            new_row = dict(base_row)
            new_row[ic["entry"]] = new_entry
            if rec.get("write_required_level", True):
                new_row[ic["reqlevel"]] = rec["new_required_level"]
            if rec.get("new_item_level") is not None:
                new_row[ic["itemlevel"]] = rec["new_item_level"]
            for sv_col, new_val in rec.get("new_stat_values", {}).items():
                new_row[sv_col] = new_val
            for st_col, new_type in rec.get("new_stat_types", {}).items():
                new_row[st_col] = new_type
            for spellid_col in rec.get("cleared_spell_slots", []):
                new_row[spellid_col] = 0
            if rec.get("new_armor") is not None:
                new_row[ic["armor"]] = rec["new_armor"]
            if rec.get("new_dmg_min") is not None:
                new_row[ic["dmgmin"]] = rec["new_dmg_min"]
            if rec.get("new_dmg_max") is not None:
                new_row[ic["dmgmax"]] = rec["new_dmg_max"]
            if rec.get("new_random_property") is not None and ic.get("randomproperty"):
                new_row[ic["randomproperty"]] = rec["new_random_property"]
            if rec.get("new_random_suffix") is not None and ic.get("randomsuffix"):
                new_row[ic["randomsuffix"]] = rec["new_random_suffix"]

            col_names = list(new_row.keys())
            insert_stmt = (
                f"INSERT INTO item_template ({', '.join('`' + c + '`' for c in col_names)}) "
                f"VALUES ({', '.join(['%s'] * len(col_names))})"
            )
            insert_params = [new_row[c] for c in col_names]
            print(f"[ITEM][CLONE] entry={rec['entry']} -> new_entry={new_entry} ({rec['name']})")
            if sql_writer:
                sql_writer.statement(insert_stmt, insert_params)
                sql_writer.mark_processed(ITEM_STATE_TABLE, rec["entry"], f"cloned -> {new_entry}")
            if not dry_run:
                with conn.cursor() as cur:
                    cur.execute(insert_stmt, insert_params)
                mark_processed(conn, ITEM_STATE_TABLE, rec["entry"], f"cloned -> {new_entry}")

            # Repoint quest/creature sources to the clone
            for src in rec.get("sources", []):
                if src["type"] == "quest":
                    msg = (f"[ITEM][REPOINT] quest {src['quest_id']}: item {rec['entry']} -> {new_entry} "
                           f"(manual check needed - update the matching RewardItem/RewardChoiceItemID column)")
                    print(msg)
                    if sql_writer:
                        sql_writer.comment(msg)
                elif src["type"] == "creature":
                    msg = (f"[ITEM][REPOINT] creature {src['creature_entry']} loot: item {rec['entry']} -> "
                           f"{new_entry} (manual check needed - update creature_loot_template.Item)")
                    print(msg)
                    if sql_writer:
                        sql_writer.comment(msg)
            n_cloned += 1
    elif plan.get("cloned"):
        print(f"[ITEM] Skipping {len(plan['cloned'])} clone-required items (pass --include-clones to handle them).")

    return n_simple, n_cloned


def apply_spell_plan(conn, plan, dry_run, sql_writer=None):
    """Applies plans/spell_plan.json to the live spell_dbc table. Same-ID
    overwrite (no cloning) by design - see spell_nerf.py's module docstring.
    For each spell: if spell_dbc already has an override row for that ID, a
    narrow UPDATE touches only the changed effect columns (preserving
    whatever else that override customized); otherwise a full INSERT ...
    ON DUPLICATE KEY UPDATE writes the complete nerfed row (built from
    Spell.csv's native definition) as spell_dbc's new override for that ID."""
    spells = plan.get("spells", [])
    if not spells:
        return 0

    if not dry_run:
        ensure_state_table(conn, SPELL_NERF_STATE_TABLE)
    if sql_writer:
        sql_writer.declare_state_table(SPELL_NERF_STATE_TABLE)
        sql_writer.comment("=== Spell nerfs (same-ID overwrite in spell_dbc) ===")

    n = 0
    for rec in spells:
        spell_id = rec["spell_id"]
        new_row = rec["new_row"]
        all_columns = list(new_row.keys())

        with conn.cursor() as cur:
            cur.execute("SELECT 1 AS x FROM spell_dbc WHERE ID = %s", (spell_id,))
            already_overridden = cur.fetchone() is not None

        effect_changes = [(e["slot"], e["old_magnitude"], e["new_magnitude"]) for e in rec["effect_changes"]]

        if already_overridden:
            stmt, params = spell_lookup.spell_dbc_targeted_update_sql(spell_id, effect_changes)
            mode = "UPDATE (existing override)"
        else:
            stmt, params = spell_lookup.spell_dbc_upsert_sql(new_row, all_columns)
            mode = "INSERT (new override)"

        changes_str = ", ".join(f"slot{e['slot']} {e['kind']} {e['old_magnitude']}->{e['new_magnitude']}"
                                 for e in rec["effect_changes"])
        outside_flag = " [ALSO CAST OUTSIDE TARGET SET]" if rec.get("has_outside_caster") else ""
        print(f"[SPELL] id={spell_id} ({rec.get('name')}) {mode}: {changes_str}{outside_flag}")

        if sql_writer:
            sql_writer.statement(stmt, params)
            sql_writer.mark_processed(SPELL_NERF_STATE_TABLE, spell_id, changes_str)
        if not dry_run:
            with conn.cursor() as cur:
                cur.execute(stmt, params)
            mark_processed(conn, SPELL_NERF_STATE_TABLE, spell_id, changes_str)
        n += 1

    return n


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--apply", action="store_true", help="Actually write to the DB (default is dry-run)")
    parser.add_argument("--include-clones", action="store_true",
                         help="Also handle entries shared with non-target maps/content")
    parser.add_argument("--skip-creatures", action="store_true")
    parser.add_argument("--skip-quests", action="store_true")
    parser.add_argument("--skip-items", action="store_true")
    parser.add_argument("--skip-spells", action="store_true")
    parser.add_argument("--export-sql", metavar="PATH",
                         help="Write every generated statement, fully substituted and escaped, to this "
                              "file as a standalone .sql script. Works with or without --apply. "
                              "Defaults to an auto-named file when running as a dry run (see --no-export-sql "
                              "to suppress that).")
    parser.add_argument("--no-export-sql", action="store_true",
                         help="Suppress the automatic SQL export that otherwise happens on a dry run.")
    args = parser.parse_args()

    dry_run = not args.apply

    export_path = args.export_sql
    if export_path is None and dry_run and not args.no_export_sql:
        export_path = f"executor_changes_{time.strftime('%Y%m%d_%H%M%S')}.sql"

    if dry_run:
        print("=== DRY RUN (no changes will be written to the DB; pass --apply to execute) ===")
        if export_path:
            print(f"    A standalone SQL file will be written to: {export_path}")
            print(f"    --apply goes through Python/pymysql one statement at a time and can be slow for "
                  f"large runs. Running this file directly instead is much faster, e.g.:")
            print(f"        mysql -h <host> -u <user> -p <database> < {export_path}")
        print()
    else:
        print("=== APPLYING CHANGES TO LIVE DATABASE ===\n")
        confirm = input("Type YES to confirm you want to modify the database: ")
        if confirm != "YES":
            print("Aborted.")
            return

    creature_plan, quest_plan, item_plan, spell_plan = load_plans()

    with get_connection(autocommit=False) as conn:
        sql_writer = SQLWriter(conn, export_path) if export_path else None
        try:
            if not args.skip_creatures and (creature_plan["simple"] or
               (args.include_clones and creature_plan["cloned"])):
                make_backup(conn, "creature_template", dry_run, sql_writer)
                if args.include_clones and creature_plan["cloned"]:
                    make_backup(conn, "creature", dry_run, sql_writer)
            if not args.skip_quests and quest_plan.get("quests"):
                make_backup(conn, "quest_template", dry_run, sql_writer)
            if not args.skip_items and (item_plan.get("simple") or item_plan.get("cloned")):
                make_backup(conn, "item_template", dry_run, sql_writer)
            if not args.skip_spells and spell_plan.get("spells"):
                make_backup(conn, "spell_dbc", dry_run, sql_writer)

            n_simple = n_cloned = n_quests = n_items_simple = n_items_cloned = n_spells = 0
            if not args.skip_creatures:
                n_simple, n_cloned = apply_creature_plan(
                    conn, creature_plan, dry_run, args.include_clones, sql_writer)
            if not args.skip_quests:
                n_quests = apply_quest_plan(conn, quest_plan, dry_run, sql_writer)
            if not args.skip_items and item_plan:
                n_items_simple, n_items_cloned = apply_item_plan(
                    conn, item_plan, dry_run, args.include_clones, sql_writer)
            if not args.skip_spells and spell_plan:
                n_spells = apply_spell_plan(conn, spell_plan, dry_run, sql_writer)

            if not dry_run:
                conn.commit()
                print("\nCOMMITTED.")
            else:
                print("\nDry run complete, nothing written to the DB.")

            if sql_writer:
                sql_writer.flush()
                print(f"SQL script written to {export_path}")

            print(f"\nCreatures updated (simple): {n_simple}")
            print(f"Creatures cloned:           {n_cloned}")
            print(f"Quests updated:             {n_quests}")
            print(f"Items updated (simple):     {n_items_simple}")
            print(f"Items cloned:               {n_items_cloned}")
            print(f"Spells nerfed:               {n_spells}")

        except Exception:
            if not dry_run:
                conn.rollback()
                print("\n[ERROR] Transaction rolled back, no changes were kept.")
            raise


if __name__ == "__main__":
    main()
